CREATE DATABASE RetailInventory
GO

USE RetailInventory;

CREATE TABLE Company
(CompanyID		VARCHAR(10)		NOT NULL PRIMARY KEY,
Name			VARCHAR(30)		NOT NULL,
PhoneNumber		VARCHAR(14)		NOT NULL);

CREATE TABLE Price
(PriceID		VARCHAR(15)		NOT NULL PRIMARY KEY,
Price			MONEY			NOT NULL,
StartDate		SMALLDATETIME	NOT NULL,
EndDate			SMALLDATETIME	NOT NULL);

CREATE TABLE Product
(SKU			VARCHAR(8)		NOT NULL PRIMARY KEY,
Name			VARCHAR(30)		NOT NULL,
CompanyID		VARCHAR(10)		NOT NULL REFERENCES Company (CompanyID),
Cost			MONEY			NOT NULL,
Amount			INT				NOT NULL DEFAULT 0);

CREATE TABLE Item
(UPC			VARCHAR(15)		NOT NULL PRIMARY KEY,
Name			VARCHAR(30)		NOT NULL,
SKU				VARCHAR(8)		NOT NULL REFERENCES Product (SKU));


CREATE TABLE ItemPrice
(ItemPriceID	VARCHAR(15)		NOT NULL PRIMARY KEY,
PriceID		VARCHAR(15)		NOT NULL REFERENCES Price (PriceID),
UPC			VARCHAR(15)		NOT NULL REFERENCES Item (UPC));